- name: Gather information about Azure VMs
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection

  tasks:
    - name: Get list of all VMs in a resource group
      azure.azcollection.azure_rm_virtualmachine_info:
        resource_group: myResourceGroup
      register: vm_info

    - name: Print VM details
      debug:
        var: vm_info.vms
