- name: Install Git, Python and configure Nginx on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present
    - name: Install python
      package:
        name: python
        state: present
   
    - name: Install and configure nginx for static website hosting
      hosts: webservers
      become: yes

    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Add user to group root
      user:
        name: "ec2-user"
        groups: root
        state: present

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Add nginx configuration
      copy:
        src: /home/runner/static-site-config
        dest: /etc/nginx/sites-available/
        owner: "ec2-user"
        group: root
        mode: '0644'

    - name: Enable website configuration
      file:
        src: /etc/nginx/sites-available/static-site-config
        dest: /etc/nginx/sites-enabled/static-site-config
        state: link

    - name: Ensure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
