- name: Deploy AKS with User and System pool
  hosts: localhost
  connection: local

  tasks:
    - name: Create an AKS instance With A System Node Pool & A User Node Pool
      azure_rm_aks:
        name: myAKSzaObrisat
        resource_group: rg-dinko
        location: westeurope
        dns_prefix: akstest
        enable_rbac: true
        kubernetes_version: 1.32.7
        linux_profile:
          admin_username: azureuser
          ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQgs3VCgwcdd/7zvCzVgllrseL6LpW3hko+2D2Jz1FEkjBJ4wCyvEzRP1Q+O6qBbPqDj0Mg2sn1NlbZ+iUZsk2ZLN3wY4eZClHx3MvNx/K0Ad2o+RNayypdbK1+BIw+1K6qHpTV4KrqykdKSMQfijQcj55s4Aqvoz18EifHF3TsbmHz7jArb/R5W/6pLaRLkR8W2dVSdfqCnjWj5OznoZamiUdFGArrKkJ3SMFE0ncXwILRjlHGJPyvOvmuC9YeM3H6nS2dZ991LHlHsnELkwFmflagayECBEU1wYX628thB6KBBnyhYUxdW8T+Y4+fhsxGGPt1nIcintsPG+wf6fkSAnluU986TuvnntSn4wesB/XX7BIaOyo2TY4lvuIkBHDnHARs9hA9/lrUJVse0lmylorfFMHwIa06JBGKYxZN6Q8k4AhTvOEBCOXwuw5HzmXyi9JvdhEdmrYs4NrOCWDkGGkEUfbBIXPj3suVMuZ59l3g5m5S4SQ7z9Uq7ywnVFOQTnOpo9dv6b0iR8uVvOpUARM4SMDyFZN3wyvMDfBtNkNR9e73VkkVQWB/DN16nV+tmedKHkkNwCG2+nFmvt+bdyT2q4G6p7GsIi1M77zL+SDFsKNGxuqjYxiN8UtMFYMzVbwDeDYNsLzug5TriJsowJdVh7JnyYb2Df7pEUR+w== keglic@yahoo.com"
        service_principal:
          client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
          client_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
        agent_pool_profiles:
          - name: default
            count: 1
            vm_size: Standard_B2s
            enable_auto_scaling: true
            type: VirtualMachineScaleSets
            mode: System
            max_count: 3
            min_count: 1
            tags:
              key1: value1
          - name: user
            count: 1
            vm_size: Standard_D2_v2
            enable_auto_scaling: true
            type: VirtualMachineScaleSets
            mode: User
            max_count: 3
            min_count: 1

      - name: Create a k8s namespace
        kubernetes.core.k8s:
          name: testing
          api_version: v1
          kind: Namespace
          state: present
