- name: Deploy AKS with User and System pool
  hosts: localhost
  connection: local

  vars:
    k8sconfig:
      cluster_name: myAKSzaObrisat
      resource_group: rg-dinko

    _aks_module_params:
      name: "{{ k8sconfig.cluster_name }}"
      resource_group: "{{ k8sconfig.resource_group }}"
      location: westeurope
      dns_prefix: akstest
      enable_rbac: true
      kubernetes_version: 1.32.7
      linux_profile:
        admin_username: azureuser
        ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQgs3VCgwcdd/7zvCzVgllrseL6LpW3hko+2D2Jz1FEkjBJ4wCyvEzRP1Q+O6qBbPqDj0Mg2sn1NlbZ+iUZsk2ZLN3wY4eZClHx3MvNx/K0Ad2o+RNayypdbK1+BIw+1K6qHpTV4KrqykdKSMQfijQcj55s4Aqvoz18EifHF3TsbmHz7jArb/R5W/6pLaRLkR8W2dVSdfqCnjWj5OznoZamiUdFGArrKkJ3SMFE0ncXwILRjlHGJPyvOvmuC9YeM3H6nS2dZ991LHlHsnELkwFmflagayECBEU1wYX628thB6KBBnyhYUxdW8T+Y4+fhsxGGPt1nIcintsPG+wf6fkSAnluU986TuvnntSn4wesB/XX7BIaOyo2TY4lvuIkBHDnHARs9hA9/lrUJVse0lmylorfFMHwIa06JBGKYxZN6Q8k4AhTvOEBCOXwuw5HzmXyi9JvdhEdmrYs4NrOCWDkGGkEUfbBIXPj3suVMuZ59l3g5m5S4SQ7z9Uq7ywnVFOQTnOpo9dv6b0iR8uVvOpUARM4SMDyFZN3wyvMDfBtNkNR9e73VkkVQWB/DN16nV+tmedKHkkNwCG2+nFmvt+bdyT2q4G6p7GsIi1M77zL+SDFsKNGxuqjYxiN8UtMFYMzVbwDeDYNsLzug5TriJsowJdVh7JnyYb2Df7pEUR+w== keglic@yahoo.com"

      service_principal:
        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        client_secret: "{{ lookup('env', 'AZURE_SECRET') }}"

      agent_pool_profiles:
        - name: default
          count: 1
          vm_size: Standard_B2s
          enable_auto_scaling: true
          type: VirtualMachineScaleSets
          mode: System
          max_count: 3
          min_count: 1
          tags:
            key1: value1

        - name: user
          count: 1
          vm_size: Standard_D2_v2
          enable_auto_scaling: true
          type: VirtualMachineScaleSets
          mode: User
          max_count: 3
          min_count: 1

  tasks:
    - name: Create an AKS instance With A System Node Pool & A User Node Pool
      azure.azcollection.azure_rm_aks: "{{ _aks_module_params }}"
      register: azure_aks_cluster

    - name: Store kube/config in tempfile
      ansible.builtin.tempfile:
        state: file
      register: aks_kubeconfig_tmpfile

    - name: Azure CLI login
      command: >
        az login --service-principal -u {{ lookup('env', 'AZURE_CLIENT_ID') }} -p {{ lookup('env', 'AZURE_SECRET') }} -t 'a349a914-163f-4221-877b-69ff3cc2a61e'

    - name: Retrieve kubeconfig from AKS
      command: >
        az aks get-credentials
        --resource-group {{ k8sconfig.resource_group }}
        --name {{ k8sconfig.cluster_name }}
        --file {{ aks_kubeconfig_tmpfile.path }}
        --overwrite-existing
        --admin
      register: kubeconfig_cmd    


    - name: Debug kubeconfig file path
      debug:
        msg: "Kubeconfig file path: {{ aks_kubeconfig_tmpfile.path }}"

    - name: Check kubeconfig file content
      command: cat {{ aks_kubeconfig_tmpfile.path }}
      register: kubeconfig_file_content
        

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ aks_kubeconfig_tmpfile.path }}"
        name: testing
        api_version: v1
        kind: Namespace
        state: present

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ aks_kubeconfig_tmpfile.path }}"
        name: dinko
        api_version: v1
        kind: Namespace
        state: present

    - name: create resource using name generated by the server
      kubernetes.core.k8s:
        kubeconfig: "{{ aks_kubeconfig_tmpfile.path }}"
        state: present
        namespace: testing
        generate_name: pod-
        definition:
          apiVersion: v1
          kind: Pod
          spec:
            containers:
            - name: py
              image: python:3.7-alpine
              imagePullPolicy: IfNotPresent

    - name: Create a Service object from an inline definition
      kubernetes.core.k8s:
        kubeconfig: "{{ aks_kubeconfig_tmpfile.path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: web
            namespace: testing
            labels:
              app: galaxy
              service: web
          spec:
            selector:
              app: galaxy
              service: web
            ports:
            - protocol: TCP
              targetPort: 8000
              name: port-8000-tcp
              port: 8000

    - name: Remove a managed Azure Container Services (AKS) instance
      azure_rm_aks:
        name: myAKSzaObrisat
        resource_group: rg-dinko
        state: absent
