- name: Create an Azure Linux VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection

  vars:
    resource_group: rg-dinko
    location: "eastus"

  tasks:
    - name: Create a linux app service plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: myAppPlan
        location: eastus
        sku: S1
        is_linux: true
        number_of_workers: 1

  
    - name: Display facts output
      debug:
        var: output
